### ISSUE TITLE
error ELIFECYCLE

### ISSUE THREAD

**Issue by naufalized** [Synthesized-Infinity/Whatsapp-Botto-Xre#22]
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /opt/app-root/src/Whatsapp-Botto-Xre/node_modules/@tensorflow/tfjs-node/lib/napi-v6/../../deps/lib/libtensorflow.so.2)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/app-root/src/Whatsapp-Botto-Xre/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-botto-xre@1.0.0 start: `node dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the whatsapp-botto-xre@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/app-root/src/.npm/_logs/2021-05-06T15_57_53_880Z-debug.log

**Comment by SheIITear** [comment]
Try running  `sudo apt install libstdc++6` and then try again.
