### ISSUE TITLE
Deploy is successful but app is crashing

### ISSUE THREAD

**Issue by naveen221001** [Synthesized-Infinity/Whatsapp-Botto-Xre#54]
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

Application Logs
2021-07-04T21:04:49.047970+00:00 app[web.1]:     at Object.<anonymous> (/app/dist/index.js:10:8)
2021-07-04T21:04:49.047971+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2021-07-04T21:04:49.047971+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2021-07-04T21:04:49.047972+00:00 app[web.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-07-04T21:04:49.048078+00:00 app[web.1]: (node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-07-04T21:04:49.048192+00:00 app[web.1]: (node:21) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-07-04T21:04:49.876898+00:00 heroku[web.1]: Process exited with status 0
2021-07-04T21:04:49.955572+00:00 heroku[web.1]: State changed from starting to crashed
2021-07-04T21:05:04.374688+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=naveen2210.herokuapp.com request_id=582ae886-5176-4c3d-ac28-d64b24d6e859 fwd="157.40.144.116" dyno= connect= service= status=503 bytes= protocol=https
2021-07-04T21:05:11.430480+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=naveen2210.herokuapp.com request_id=54d43e32-989a-48e5-ae05-7e8dcbaa2297 fwd="157.40.144.116" dyno= connect= service= status=503 bytes= protocol=https
2021-07-04T21:12:19.548020+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=naveen2210.herokuapp.com request_id=9126a1cf-0620-4b8e-94b0-a0c7bd73737d fwd="157.40.144.116" dyno= connect= service= status=503 bytes= protocol=https
2021-07-04T21:12:22.739132+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=naveen2210.herokuapp.com request_id=a5730d33-7c23-4570-9759-1f391b3a99b9 fwd="157.40.144.116" dyno= connect= service= status=503 bytes= protocol=https

![Screenshot (4)](https://user-images.githubusercontent.com/72919423/124399766-4677d700-dd3b-11eb-9b7f-4f2825ab6dfd.png)

![Screenshot (2)](https://user-images.githubusercontent.com/72919423/124399688-be91cd00-dd3a-11eb-9a97-db7e7e036110.png)

**Comment by naveen221001** [comment]
Done!

**Comment by SomnathDas** [comment]
@naveen221001 Make sure to comment the solution if you found any before closing as it can help others. Thank you!
